### ISSUE TITLE
TypeError: react_linkedin_insight__WEBPACK_IMPORTED_MODULE_0___default.a.init is not a function

### ISSUE THREAD

**Issue by theoldcounty** [jelleklaver/react-linkedin-insight#12]
I am getting the following error - trying to invoke the init function
```js
TypeError: react_linkedin_insight__WEBPACK_IMPORTED_MODULE_0___default.a.init is not a function
```
I've tried 
```js
LinkedInTag.init("PARTNERID", "dc", false);
LinkedInTag.init("PARTNERID");
```

**Comment by jelleklaver** [comment]
How do you import the package?

**Comment by theoldcounty** [comment]
npm i react-linkedin-insight

**Comment by theoldcounty** [comment]
import LinkedInTag from 'react-linkedin-insight';

**Comment by theoldcounty** [comment]
`LinkedInTag.track("xx");`  --- similar problem - nothing appears to work

**Comment by jelleklaver** [comment]
It seems like somehow you've got the Class as import in stead of the instance defined using `export default new LinkedInTag()`.

Could you try if the following solves your problem?

```js
import {LinkedInTag} from 'react-linkedin-insight';

linkedintag = new LinkedInTag();
linkedintag.init("PARTNERID");
```

**Comment by theoldcounty** [comment]
```js
TypeError: react_linkedin_insight__WEBPACK_IMPORTED_MODULE_0__.LinkedInTag is not a constructor

 let linkedintag = new LinkedInTag();
 linkedintag.init("PARTNERID");
```

**Comment by jelleklaver** [comment]
Did you import using the curly braces?

**Comment by theoldcounty** [comment]
yeah I've followed - nothing works

**Comment by theoldcounty** [comment]
`import {LinkedInTag} from 'react-linkedin-insight';`
--LinkedInTag I think that comes out as undefined too

**Comment by jelleklaver** [comment]
Could you try if versions 0.1.0 or 0.05 do work out fine?

**Comment by theoldcounty** [comment]
no both failed

**Comment by jelleklaver** [comment]
If 0.0.5 doesn't work with the example in the README, then it seems to be related to the way your webpack imports the package. I guess it might be something in your webpack configuration that breaks the import. Do other packages work fine? What is your webpack config? I'm not a hero with webpack, so I'm not sure if you're at the right place here to debug this.

**Comment by theoldcounty** [comment]
its just a standard create react app - there isn't anything off with the webpack config -- its still not ejected - its standard. I've not see any other issues like this before.

**Comment by theoldcounty** [comment]
Just a standard https://github.com/facebook/create-react-app

**Comment by theoldcounty** [comment]
just to prove I am not going crazy -- I just tried to get this working in a sandbox and its the same issue.
https://codesandbox.io/s/purple-thunder-sek0z

**Comment by jelleklaver** [comment]
Your codesandbox does seem to work with version `0.0.5` however. So you can use that one for now, I'll look into it when I have time. I guess it has something to do with adding the named export in `0.1.0`.

**Comment by jelleklaver** [comment]
Allright, there seemed to be an issue with the generated distribution. I kept testing with the actual source code, so I couldn't correctly reproduce the issue at first. I've published 0.1.2 which should resolve this issue.

**Comment by knightspore** [comment]
Having this same error with Next.js

```
TypeError: react_linkedin_insight__WEBPACK_IMPORTED_MODULE_9__.LinkedInTag.init is not a function
```

**Comment by jelleklaver** [comment]
Hi @knightspore, can you elaborate a bit more? Please share (an example of) what your code looks like and which version of react-linkedin-insight you're using.

**Comment by knightspore** [comment]
@jelleklaver I'm sorted now, my apologies! I'd had:
```js
import {LinkedInTag} from 'react-linkedin-insight';

linkedintag = new LinkedInTag();
linkedintag.init("PARTNERID");
```

While I needed: 
```js
import LinkedInTag from 'react-linkedin-insight';

linkedintag = new LinkedInTag();
linkedintag.init("PARTNERID");
```
